sudo: required
services:
  - docker

before_install:
  - docker build -t ganeshprabh07/react-test -f ./client/DockerFile.dev ./client

script:
  - docker run -e CI=true ganeshprabh07/react-test npm test -- --coverage

after_success:
  - docker build -t ganeshprabh07/multi-client ./client
  - docker build -t ganeshprabh07/multi-nginx ./nginx
  - docker build -t ganeshprabh07/multi-server ./server
  - docker build -t ganeshprabh07/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push to docker HUB
  - docker push ganeshprabh07/multi-client
  - docker push ganeshprabh07/multi-nginx
  - docker push ganeshprabh07/multi-server
  - docker push ganeshprabh07/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-164116308934
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY